### ISSUE TITLE
signing error 

### ISSUE THREAD

**Issue by future-guard** [siacentral/sia-lite-wallet-web#8] opened 2020-08-05 08:21 UTC
POST request error; error accepting transaction set:consensus conflict: provided transaction set is standalone and invalid: invalid signature]

above error occur when i signing with ledger nano s. 

how can i resolve this issue?

yesterday it was working properly

**Comment by n8maninger** [comment] 2020-08-05 11:15
So you were able to send a transaction with the Ledger Nano S yesterday, but not today? I've tried to replicate the issue with my own Ledger, but can't seem to on my end. 

You could try deleting the wallet and recreating it.
Have you tried clearing your cache with a hard refresh: `CTRL+F5` or `CMD+SHIFT+R`?

+ How much SC were you trying to send? 
+ What browser and operating system?
+ How many outputs?

**Comment by future-guard** [comment] 2020-08-06 02:01
sorry for short description before i wrote.

My Env : 
MacOS, Chrome

What i did before creating issue for self resolve :
1. cache clear(cmd+shift+r)
2. delete and reinstall ledger nano s sia app 
3. delete and import wallet again with ledger

 - Are you accessing the lite wallet on https://wallet.siacentral.com ?
 > yes. absolutely yes.
 - Do you have multiple Ledger?
 > no. one ledger.
 - What browser and operating system?
 > MacOS, Chrome
 - How much SC were you trying to send?
 > 40,000,000 SC
 - How many outputs?
 > 1 output. 

and i got a weired things on it. It seems there is final confirmation checking on ledger when i trying to transfer
but in this case, final check didnt show up on ledger but it activate transfer button on web wallet.
and then i click it web wallet just showing errors above one.

**Comment by n8maninger** [comment] 2020-08-06 02:54
What do you mean by final check not showing up? A single signature transaction should be 5 or 7 double button presses followed by a reject/accept single button press. Is that not showing up?

The Ledger is very difficult to troubleshoot since everything happens on the device.. Sorry for all the additional questions. I'll keep trying to reproduce it with my Nano S, but any additional details you can provide from troubleshooting might help locate the issue. I've been able to send 15 transactions from my own device with no issue while testing.

We both use the same browser and OS. I'm on Catalina 10.15.6 and Chrome 84.0.4147.105. 

Ledger Live can interfere with the lite wallet. Make sure that is closed. Is your Ledger Nano S on firmware v1.6.0 and Sia App v0.4.2?

Would it be possible to try from another machine? 
Can you try with a different USB cable?

**Comment by n8maninger** [comment] 2020-09-04 23:49
Closing due to lack of information and inability to reproduce. If you're still having an issue, I'm happy to reopen

**Closed by n8maninger** 2020-09-04 23:49 UTC
